POST  http://localhost:3000/signin
Content-Type: application/json

{
  "email": "qksyo10@yandex.ru",
  "password": "1010"
}

###

GET  http://localhost:3000/localhost:3000/cards



###

POST http://localhost:3000/cards/
Content-Type: application/json

{
  "name": "dadadad",
  "link": "https://sun9-50.userapi.com/s/v1/ig2/89BsWm9BrMy_CuoMx-i9wZaW9Bs9-WDdTTFwvZf3UDrDcbNkzIxK4pEYKZvCWnLevBFa1JmQyqmBBgVCYsxzA4E4.jpg?size=1125x1379&quality=96&type=album"
}

###

GET http://localhost:3000/sign-out

###

POST http://localhost:3000/cards
Content-Type: application/json

{
  "name": "для удаления",
  "link": "https://sun9-50.userapi.com/s/v1/ig2/89BsWm9BrMy_CuoMx-i9wZaW9Bs9-WDdTTFwvZf3UDrDcbNkzIxK4pEYKZvCWnLevBFa1JmQyqmBBgVCYsxzA4E4.jpg?size=1125x1379&quality=96&type=album"
}