POST  http://localhost:3000/signin
Content-Type: application/json

{
  "email": "qksyo2223@yandex.ru",
  "password": "3213"
}

###

GET  http://130.193.40.147/cards/



###

POST http://localhost:3000/cards/
Content-Type: application/json

{
  "name": "dadadad",
  "link": "https://sun9-50.userapi.com/s/v1/ig2/89BsWm9BrMy_CuoMx-i9wZaW9Bs9-WDdTTFwvZf3UDrDcbNkzIxK4pEYKZvCWnLevBFa1JmQyqmBBgVCYsxzA4E4.jpg?size=1125x1379&quality=96&type=album"
}

###

GET http://localhost:3000/users/me


###

POST http://localhost:3000/cards
Content-Type: application/json

{
  "name": "для удаления",
  "link": "https://sun9-50.userapi.com/s/v1/ig2/89BsWm9BrMy_CuoMx-i9wZaW9Bs9-WDdTTFwvZf3UDrDcbNkzIxK4pEYKZvCWnLevBFa1JmQyqmBBgVCYsxzA4E4.jpg?size=1125x1379&quality=96&type=album"
}